/**
 * Public credential routes — single source of truth for all
 * unauthenticated credential endpoints.
 *
 * Aug 2026: previously these routes were scattered across three files
 * (credential-public.ts, credential-custom.ts, credential-fallback.ts)
 * with overlapping paths and inconsistent auth config. credential-custom.ts
 * in particular exposed export/import/revoke as auth:false public routes
 * (a security issue). credential-fallback.ts existed only as a "last
 * resort" listing. All three have been consolidated here.
 *
 * Paths in this file are WITHOUT the /api prefix — Strapi's config/api.ts
 * prepends it automatically (config/api.ts: rest.prefix: '/api').
 *
 * @see docs/backend.md#api-structure
 * @see docs/known-issues-and-dev-notes.md item 11
 */

export default {
  routes: [
    { method: 'POST', path: '/credentials/:id/check-recipient', handler: 'credential.checkRecipient', config: { auth: false } },
    // ---------------------------------------------------------------
    // Core read-only routes — generated by the content-type router but
    // re-declared here with auth:false for public access.
    // ---------------------------------------------------------------

    // Public listing (used by sitemap generation, public badge boards)
    {
      method: 'GET',
      path: '/credentials',
      handler: 'credential.find',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },

    // Public single-credential detail (verification page, embed)
    {
      method: 'GET',
      path: '/credentials/:id',
      handler: 'credential.findOne',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },

    // ---------------------------------------------------------------
    // Verification & validation — intentionally unauthenticated
    // so anyone can verify a credential by its public ID.
    // ---------------------------------------------------------------

    // Cryptographically verify a credential by credentialId
    {
      method: 'GET',
      path: '/credentials/:id/verify',
      handler: 'credential.verify',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },

    // Validate an externally-submitted credential (OBv3 JSON body)
    {
      method: 'POST',
      path: '/credentials/validate',
      handler: 'credential.validate',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },

    // ---------------------------------------------------------------
    // Certificate/image generation — intentionally unauthenticated
    // so badge recipients can share rendered certificate images.
    // ---------------------------------------------------------------

    // SVG certificate by credential ID
    {
      method: 'GET',
      path: '/credentials/:id/certificate',
      handler: 'credential.getCertificate',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },

    // Short-form direct certificate URL (/verify/<id>)
    {
      method: 'GET',
      path: '/verify/:id',
      handler: 'credential.getDirectCertificate',
      config: {
        auth: false,
        policies: [],
        middlewares: [],
      },
    },
  ],
};
