// Uses only the ephemeral fixture created by backend/scripts/qa/portal-http.cjs.
import { chromium, expect } from '@playwright/test'
import { readFileSync, mkdirSync } from 'node:fs'
const fixture = JSON.parse(readFileSync(process.argv[2], 'utf8'))
const browser = await chromium.launch({ executablePath: process.env.QA_CHROMIUM, headless: true, args: ['--no-sandbox'] })
const artifacts = '/tmp/certo-portal-render'
mkdirSync(artifacts, { recursive: true })
const base = 'http://127.0.0.1:19300'
const credentialPath = `/credentials/${encodeURIComponent(fixture.id)}`
let count = 0
const check = async (fn) => { await fn(); count++ }
const errors = []
async function session(user, token, options = {}) {
  const ctx = await browser.newContext({ locale: 'en-US', viewport: { width: 1360, height: 960 }, ...options })
  // Block third-party fonts/analytics/images in this local-only QA session.
  await ctx.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' || route.request().url().startsWith('data:') ? route.continue() : route.abort())
  if (token) await ctx.addInitScript(({ user, token }) => { localStorage.setItem('token', token); localStorage.setItem('user', JSON.stringify(user)) }, { user, token })
  const page = await ctx.newPage()
  const goto = page.goto.bind(page)
  page.goto = (url, options = {}) => goto(url, { waitUntil: 'networkidle', ...options })
  page.on('pageerror', e => { errors.push(e.message); console.error('PAGE_ERROR', e.message) })
  return { ctx, page }
}
// Make the test repeatable after a previously interrupted browser run.
await fetch(`http://127.0.0.1:19337/api/credentials/${encodeURIComponent(fixture.id)}/privacy`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${fixture.token}` }, body: JSON.stringify({ data: { publicRecipientName: true, publicLinkActive: true } }) })
const visitor = await session()
await visitor.page.goto(base, { waitUntil: 'networkidle' })
await check(() => expect(visitor.page.locator('h1')).toHaveText('Microcredenciales de UDGPlus'))
await check(() => expect(visitor.page.locator('html')).toHaveAttribute('lang', 'es'))
await check(() => expect(visitor.page.locator('nav').getByText('Emitir', { exact: true })).toHaveCount(0))
await check(() => expect(visitor.page.locator('nav').getByText('Panel de control', { exact: true })).toHaveCount(0))
await check(() => expect(visitor.page.getByRole('heading', { name: 'Qué acredita UDGPlus' })).toBeVisible())
for (const mode of ['light', 'dark']) {
  await visitor.page.evaluate(mode => { document.documentElement.classList.toggle('dark', mode === 'dark') }, mode)
  const colors = await visitor.page.locator('nav a[href="/login"]').first().evaluate(el => {
    const s = getComputedStyle(el); return { fg: s.color, bg: s.backgroundColor }
  })
  await check(() => expect(colors).toEqual({ fg: 'rgb(255, 255, 255)', bg: 'rgb(0, 45, 84)' }))
  await visitor.page.screenshot({ path: `${artifacts}/home-${mode}.png`, fullPage: true })
}
await visitor.page.getByRole('button', { name: 'Idioma: Español' }).click()
await visitor.page.getByRole('button', { name: 'English', exact: true }).click()
await visitor.page.reload({ waitUntil: 'networkidle' })
await check(() => expect(visitor.page.locator('html')).toHaveAttribute('lang', 'en'))
await visitor.page.getByRole('button', { name: 'Language: English' }).click()
await visitor.page.getByRole('button', { name: 'Español', exact: true }).click()
await visitor.page.setViewportSize({ width: 390, height: 844 })
await visitor.page.getByRole('button', { name: /menú/i }).click()
await check(() => expect(visitor.page.locator('#mobile-menu a[href="/login"]')).toBeVisible())
await visitor.page.screenshot({ path: `${artifacts}/home-mobile.png`, fullPage: true })
await visitor.page.goto(`${base}/verify`)
await visitor.page.locator('#certificateId').fill(`${base}${credentialPath}`)
await visitor.page.locator('button[type="submit"]').click()
await check(() => expect(visitor.page.getByText('Análisis de información · prueba local', { exact: true }).first()).toBeVisible())
await visitor.page.screenshot({ path: `${artifacts}/verify-mobile.png`, fullPage: true })
await visitor.page.goto(`${base}${credentialPath}`)
await check(() => expect(visitor.page.getByRole('link', { name: 'Qué acredita esta credencial' })).toHaveAttribute('href', 'https://catalog.example.test/skill'))
const owner = await session(fixture.user, fixture.token)
await owner.page.goto(`${base}/dashboard`)
await check(() => expect(owner.page.getByRole('heading', { name: 'Mis credenciales', exact: true })).toBeVisible())
await check(() => expect(owner.page.locator('nav a[href="/saberes-previos"]')).toBeVisible())
await check(() => expect(owner.page.locator('nav a[href="/issue"]')).toHaveCount(0))
await check(() => expect(owner.page.getByRole('link', { name: 'Ver descargas y privacidad' })).toBeVisible())
const historyDownload = owner.page.waitForEvent('download')
await owner.page.getByRole('button', { name: 'Exportar historial CLR' }).click()
await (await historyDownload).saveAs(`${artifacts}/history.json`)
await check(() => expect(JSON.parse(readFileSync(`${artifacts}/history.json`, 'utf8')).type).toContain('ClrCredential'))
await owner.page.goto(`${base}${credentialPath}`)
await check(() => expect(owner.page.getByRole('button', { name: 'Descargar el archivo de la credencial' })).toBeVisible())
const downloadEvent = owner.page.waitForEvent('download')
await owner.page.getByRole('button', { name: 'Descargar el archivo de la credencial' }).click()
const download = await downloadEvent
await download.saveAs(`${artifacts}/credential.json`)
const signed = JSON.parse(readFileSync(`${artifacts}/credential.json`, 'utf8'))
await check(() => expect(signed.proof.jws).toBeTruthy())
await owner.page.getByLabel('Mostrar mi nombre en la página pública').uncheck()
await owner.page.getByRole('button', { name: 'Guardar privacidad' }).click()
await check(() => expect(owner.page.getByText('Privacidad guardada.', { exact: true })).toBeVisible())
await visitor.page.reload()
await check(() => expect(visitor.page.getByText('Titular verificado por UDGPlus', { exact: true })).toBeVisible())
await check(() => expect(visitor.page.getByText('Titular de prueba', { exact: true })).toHaveCount(0))
await owner.page.getByLabel('Mantener activo el enlace público').uncheck()
await owner.page.getByRole('button', { name: 'Guardar privacidad' }).click()
await owner.page.getByText('Privacidad guardada.', { exact: true }).waitFor()
await visitor.page.reload()
await check(() => expect(visitor.page.getByRole('heading', { name: 'Esta credencial no está disponible públicamente.' })).toBeVisible())
await visitor.page.goto(`${base}/verify`)
await visitor.page.getByRole('button', { name: 'Subir archivo', exact: true }).click()
await visitor.page.locator('input[type="file"]').setInputFiles(`${artifacts}/credential.json`)
await visitor.page.locator('button[type="submit"]').click()
await check(() => expect(visitor.page.getByText('Análisis de información · prueba local', { exact: true }).first()).toBeVisible())
await owner.page.goto(`${base}${credentialPath}/imprimir`)
await check(() => expect(owner.page.getByRole('heading', { name: 'Análisis de información · prueba local', exact: true })).toBeVisible())
await check(() => expect(owner.page.getByText('Titular de prueba', { exact: true })).toBeVisible())
await check(() => expect(owner.page.getByAltText('Código QR del enlace de verificación')).toBeVisible())
await check(() => expect(owner.page.getByText('Interpretar información', { exact: true })).toBeVisible())
await check(() => expect(owner.page.locator('img.badge')).toBeVisible())
await owner.page.screenshot({ path: `${artifacts}/print-screen.png`, fullPage: true })
await owner.page.evaluate(() => { window.print = () => { window.__qaPrinted = true } })
await owner.page.getByRole('button', { name: 'Descargar PDF', exact: true }).click()
await check(() => expect.poll(() => owner.page.evaluate(() => !!window.__qaPrinted)).toBe(true))
await owner.page.pdf({ path: `${artifacts}/credential-a4.pdf`, preferCSSPageSize: true, printBackground: true })
const issuer = await session(fixture.issuerUser, fixture.issuerToken)
await issuer.page.goto(base)
await check(() => expect(issuer.page.locator('nav a[href="/issue"]')).toBeVisible())
await check(() => expect(errors).toEqual([]))
await browser.close()
console.log(`PORTAL_BROWSER_PASS ${count} assertions; artifacts: ${artifacts}`)
